In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

## Create and Read

#### 1-D Array

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim

1

In [8]:
arr1.size

5

#### 2-D Array

In [9]:
arr2 = np.array([[1,2,3], [4,5,6]])

In [10]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape # (row, col)

(2, 3)

In [13]:
arr2.dtype

dtype('int64')

In [14]:
arr2.size

6

#### 3-D Array

In [15]:
arr3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
arr3.shape

(2, 2, 2)

In [17]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
arr3.size

8

In [19]:
arr3.ndim

3

#### Create random array

In [20]:
randomArr = np.random.rand(3, 2, 3)*100
randomArr

array([[[71.95225772, 75.00538089, 44.57735312],
        [24.14414751, 11.9872537 ,  9.55592066]],

       [[74.43395686, 52.25108903, 58.96480581],
        [67.00037878, 63.81727488, 23.34658892]],

       [[52.54528177, 55.92455927, 13.52524858],
        [17.37449755, 48.48065282, 10.16155908]]])

In [21]:
randomArr.dtype

dtype('float64')

In [22]:
zeroes = np.zeros((5,3,4))
zeroes

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
full = np.full((3,2,3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [24]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
arr3[1]

array([[5, 6],
       [7, 8]])

In [26]:
arr3[1][0]

array([5, 6])

In [27]:
arr3[1][0][1]

np.int64(6)

In [28]:
arr3[1,0,1]

np.int64(6)

# Update and Delete

In [35]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)
a1

array([[[0.83118453, 0.09283224],
        [0.31919704, 0.95926211],
        [0.50027882, 0.706583  ]],

       [[0.48867598, 0.6141709 ],
        [0.30979305, 0.12625459],
        [0.15103933, 0.2640547 ]]])

In [36]:
a2

array([[[0.88727184, 0.05659971],
        [0.26142399, 0.42685404],
        [0.95137061, 0.67994207]],

       [[0.89106364, 0.16908024],
        [0.81894187, 0.11663735],
        [0.73411252, 0.50252755]]])

#### Basic mathematical operations

In [37]:
 np.add(a1, a2)

array([[[1.71845637, 0.14943195],
        [0.58062103, 1.38611615],
        [1.45164944, 1.38652506]],

       [[1.37973962, 0.78325114],
        [1.12873492, 0.24289194],
        [0.88515185, 0.76658226]]])

In [39]:
np.subtract(a1, a2)

array([[[-0.05608731,  0.03623254],
        [ 0.05777305,  0.53240807],
        [-0.45109179,  0.02664093]],

       [[-0.40238765,  0.44509066],
        [-0.50914881,  0.00961724],
        [-0.58307319, -0.23847285]]])

In [40]:
np.divide(a1, a2)

array([[[0.93678678, 1.64015416],
        [1.22099366, 2.24728366],
        [0.52585062, 1.03918117]],

       [[0.54841873, 3.63242272],
        [0.37828455, 1.08245425],
        [0.20574412, 0.52545319]]])

In [41]:
np.multiply(a1, a2)

array([[[0.73748663, 0.00525428],
        [0.08344576, 0.40946491],
        [0.47595057, 0.4804355 ]],

       [[0.4354414 , 0.10384416],
        [0.2537025 , 0.014726  ],
        [0.11087986, 0.13269476]]])

#### statistical operations

In [43]:
sqrt = np.sqrt(25)
sqrt

np.float64(5.0)

In [44]:
power = np.power(2,8)
power

np.int64(256)

In [45]:
log = np.log(25)
log

np.float64(3.2188758248682006)

In [47]:
mins = np.min(a1)
mins

np.float64(0.09283224334776785)

In [48]:
maxs = np.max(a2)
maxs

np.float64(0.9513706115949387)

In [49]:
e = np.e
e 

2.718281828459045

In [56]:
val = np.power(np.e, 3.2188758)
val

np.float64(24.99999937829499)

#### Update

In [57]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [58]:
arr3[1,0, 1] = 100
arr3

array([[[  1,   2],
        [  3,   4]],

       [[  5, 100],
        [  7,   8]]])

In [61]:
arr3.sort()
arr3

array([[[  1,   2],
        [  3,   4]],

       [[  5, 100],
        [  7,   8]]])

In [62]:
# Reshape
arr3.shape

(2, 2, 2)

In [63]:
 arr3_reshape = arr3.reshape((1, 4, 2))

In [64]:
arr3_reshape

array([[[  1,   2],
        [  3,   4],
        [  5, 100],
        [  7,   8]]])

In [65]:
 arr3_reshape2 = arr3.reshape((4, 1, 2))
 arr3_reshape2

array([[[  1,   2]],

       [[  3,   4]],

       [[  5, 100]],

       [[  7,   8]]])

#### Appending and inserting

In [66]:
zeroes

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [67]:
zeroes.ndim

3

In [68]:
zeroes.shape


(5, 3, 4)

In [69]:
new_array = np.ones(zeroes.shape)
new_array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [72]:
appd = np.append(zeroes, new_array, axis=0) # axis 0 is row, axis 1 is column
appd

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# Insert

In [76]:
inserted_array = np.insert(zeroes, 2, new_array, axis=0)
inserted_array

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

#### Delete

In [78]:
arr4 = np.random.rand(3, 4, 3)
arr4

array([[[0.218991  , 0.52620354, 0.65536666],
        [0.3711867 , 0.75943874, 0.90728055],
        [0.17553541, 0.03964086, 0.27543554],
        [0.29685328, 0.5167676 , 0.31101019]],

       [[0.44617034, 0.06779987, 0.88244598],
        [0.86011393, 0.05218751, 0.29624361],
        [0.47524479, 0.5602628 , 0.39298318],
        [0.54567111, 0.17848295, 0.91662177]],

       [[0.32693308, 0.51417182, 0.817154  ],
        [0.65090806, 0.25431257, 0.49971637],
        [0.01135437, 0.57977945, 0.33702463],
        [0.96805603, 0.03211455, 0.50877815]]])

In [80]:
# delete index
arr5 = np.delete(arr4, 0, axis=1)
arr5

array([[[0.3711867 , 0.75943874, 0.90728055],
        [0.17553541, 0.03964086, 0.27543554],
        [0.29685328, 0.5167676 , 0.31101019]],

       [[0.86011393, 0.05218751, 0.29624361],
        [0.47524479, 0.5602628 , 0.39298318],
        [0.54567111, 0.17848295, 0.91662177]],

       [[0.65090806, 0.25431257, 0.49971637],
        [0.01135437, 0.57977945, 0.33702463],
        [0.96805603, 0.03211455, 0.50877815]]])

In [82]:
np.save("new_array", arr5)

In [83]:
np.load("new_array.npy")

array([[[0.3711867 , 0.75943874, 0.90728055],
        [0.17553541, 0.03964086, 0.27543554],
        [0.29685328, 0.5167676 , 0.31101019]],

       [[0.86011393, 0.05218751, 0.29624361],
        [0.47524479, 0.5602628 , 0.39298318],
        [0.54567111, 0.17848295, 0.91662177]],

       [[0.65090806, 0.25431257, 0.49971637],
        [0.01135437, 0.57977945, 0.33702463],
        [0.96805603, 0.03211455, 0.50877815]]])